name = "static"
compatibility_date = "2025-01-01"

assets = { directory = "./www", not_found_handling = "single-page-application" }

route = { pattern = "keccak-doomsday.com/*", zone_name = "keccak-doomsday.com" }
workers_dev = false

